# Generated by Django 4.0.6 on 2024-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ano',
            field=models.IntegerField(blank=True, choices=[(1, '1º ano'), (2, '2º ano'), (3, '3º ano')], null=True),
        ),
    ]
