# Generated by Django 4.0.6 on 2024-03-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0002_pessoa_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='ano',
        ),
    ]
