# Generated by Django 4.0.6 on 2024-04-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoPortfolioPW', '0003_disciplina_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='docentes',
        ),
        migrations.AddField(
            model_name='docente',
            name='disciplinas',
            field=models.ManyToManyField(related_name='docentes', to='projetoPortfolioPW.disciplina'),
        ),
    ]
