# Generated by Django 4.0.6 on 2024-04-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetoPortfolioPW', '0004_remove_disciplina_docentes_docente_disciplinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='linguagens_programacao',
        ),
    ]
