# Generated by Django 4.0.6 on 2024-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoPortfolioPW', '0005_remove_projeto_linguagens_programacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='linguagemprogramacao',
            name='projeco',
            field=models.ManyToManyField(related_name='linguagem_programacao', to='projetoPortfolioPW.projeto'),
        ),
    ]
