# Generated by Django 4.0.6 on 2024-04-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetoPortfolioPW', '0006_linguagemprogramacao_projeco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='github_repo_link',
            new_name='github_link',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='video_demo_link',
            new_name='video_link',
        ),
    ]
