# Generated by Django 4.0.6 on 2024-04-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetoPortfolioPW', '0007_rename_github_repo_link_projeto_github_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linguagemprogramacao',
            old_name='projeco',
            new_name='projeto',
        ),
    ]
