# Generated by Django 4.0.6 on 2024-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoPortfolioPW', '0008_rename_projeco_linguagemprogramacao_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linguagemprogramacao',
            name='projeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='linguagens_programacao',
            field=models.ManyToManyField(to='projetoPortfolioPW.linguagemprogramacao'),
        ),
    ]
