# Generated by Django 4.0.6 on 2024-04-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='filmes/'),
        ),
    ]
