# Generated by Django 4.0.6 on 2024-03-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_alter_album_banda_alter_album_nome_alter_banda_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
