# Generated by Django 4.0.6 on 2024-03-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_alter_album_capa_alter_banda_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(upload_to='albuns/'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.ImageField(upload_to='bandas/'),
        ),
    ]
