# Generated by Django 4.0.6 on 2024-06-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_alter_banda_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='descricao',
        ),
        migrations.AddField(
            model_name='banda',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='letra',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
