# Generated by Django 4.0.6 on 2024-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='landing_text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
