# Generated by Django 4.0.6 on 2024-03-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='post_rate',
        ),
    ]
