# Generated by Django 4.0.6 on 2024-03-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0004_post_images_alter_post_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
