# Generated by Django 4.0.6 on 2024-03-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0007_post_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate_value',
            field=models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=1, null=True),
        ),
    ]
